### PR TITLE
Remove unneeded MRS_DevOptOut variable

### PR DESCRIPTION
**Pull request by stephenatwork**
@andreiborodin this article implies that the search for build props stops as soon as one is found.
https://thomaslevesque.com/2017/09/18/common-msbuild-properties-and-items-with-directory-build-props/

So, we should be able to simply remove the MRS_DevOptOut variable?

### CODE REVIEW

**Comment by andreiborodin** [comment]
Yep, sounds good!

**Comment by stephenatwork** [comment]
> Yep, sounds good!

Thanks @andreiborodin - what's the best way to make sure I haven't broken anything with this PR?

**Comment by andreiborodin** [comment]
If you open the Unity project here: https://github.com/microsoft/MixedReality-Sharing/tree/master/libs/SpatialAlignment-Unity, it should build successfully and Assets/Dependencies folder should have DLLs.

**Pull request merged**
